[package]
name = "addressbook"
version = "0.1.0"
authors = ["Wendell Smith <wackywendell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gc = { version = "0.3", features = ["derive"] }