[package]
name = "addressbook"
version = "0.1.0"
authors = ["Wendell Smith <wackywendell@gmail.com>"]
edition = "2018"

[lib]
name = "addressbook"
path = "src/lib.rs"

[dependencies]
gc = { version = "0.3", features = ["derive"] }